-- Shimlar Database Schema
-- Reconstructed from PHP source code analysis
-- Compatible with MySQL 8.0+

CREATE DATABASE IF NOT EXISTS shimlar_game;
USE shimlar_game;

-- Players table: core player data
CREATE TABLE IF NOT EXISTS Players (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Mail VARCHAR(255) DEFAULT '',
  Pic VARCHAR(255) DEFAULT '',
  Channels INT DEFAULT 1,
  Race INT DEFAULT 1,
  Gender INT DEFAULT 1,
  Zone INT DEFAULT 1,
  Channel INT DEFAULT 0,
  Sword INT DEFAULT 0,
  Axe INT DEFAULT 0,
  Staff INT DEFAULT 0,
  Mace INT DEFAULT 0,
  Armor INT DEFAULT 0,
  Fire INT DEFAULT 0,
  Cold INT DEFAULT 0,
  Air INT DEFAULT 0,
  Arcane INT DEFAULT 0,
  Sword_bonus INT DEFAULT 0,
  Cold_bonus INT DEFAULT 0,
  Air_bonus INT DEFAULT 0,
  Arcane_bonus INT DEFAULT 0,
  Sword_m INT DEFAULT 0,
  Axe_m INT DEFAULT 0,
  Staff_m INT DEFAULT 0,
  Mace_m INT DEFAULT 0,
  Armor_m INT DEFAULT 0,
  Fire_m INT DEFAULT 0,
  Cold_m INT DEFAULT 0,
  Air_m INT DEFAULT 0,
  Arcane_m INT DEFAULT 0,
  Double_m INT DEFAULT 0,
  Lastaction VARCHAR(50) DEFAULT '',
  Ax_time DATETIME DEFAULT NULL,
  Cr VARCHAR(10) DEFAULT 'cr',
  Cr_time DATETIME DEFAULT NULL,
  Online INT DEFAULT 1,
  Ign INT DEFAULT 0,
  Banned INT DEFAULT 0,
  Mhd INT DEFAULT 0,
  Qhd INT DEFAULT 0,
  Jhd INT DEFAULT 0,
  Last_ip VARCHAR(45) DEFAULT '',
  Wrong_pw INT DEFAULT 0,
  Loc_x INT DEFAULT 1,
  Loc_y INT DEFAULT 1,
  Loc_zone INT DEFAULT 1,
  Login VARCHAR(100) DEFAULT '',
  Lastchat INT DEFAULT 0,
  Lastrole INT DEFAULT 0,
  Lastsale INT DEFAULT 0,
  Lastclan INT DEFAULT 0,
  Quests INT DEFAULT 0,
  Qnum INT DEFAULT 0,
  Pstatus INT DEFAULT 0,
  Ignlvl INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Stats table: player statistics
CREATE TABLE IF NOT EXISTS Stats (
  Id INT PRIMARY KEY,
  Name VARCHAR(100) DEFAULT '',
  Pkill INT DEFAULT 0,
  Race INT DEFAULT 0,
  Str INT DEFAULT 0,
  Dex INT DEFAULT 0,
  Vit INT DEFAULT 0,
  Ntl INT DEFAULT 0,
  Wis INT DEFAULT 0,
  Health INT DEFAULT 0,
  Gold INT DEFAULT 0,
  Banked INT DEFAULT 0,
  Exp INT DEFAULT 0,
  Lvl INT DEFAULT 1,
  Freelvl INT DEFAULT 0,
  Opponent INT DEFAULT 0,
  Status INT DEFAULT 0,
  Turns INT DEFAULT 5400,
  Clan INT DEFAULT 0,
  E_health INT DEFAULT 0,
  Fight_time DATETIME DEFAULT NULL,
  Align INT DEFAULT 0,
  Fame INT DEFAULT 0,
  Pk_time DATETIME DEFAULT NULL,
  StopSales INT DEFAULT 0,
  StopRP INT DEFAULT 0,
  Lastheal DATETIME DEFAULT NULL,
  Lasttrain DATETIME DEFAULT NULL,
  Tef INT DEFAULT 0,
  Tfc INT DEFAULT 0,
  Lastmon INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Inventory table: player items
-- i0-i38 represent item slots; accx = accessory slot; tradex = trade status
CREATE TABLE IF NOT EXISTS Inventory (
  Id INT PRIMARY KEY,
  Name VARCHAR(100) DEFAULT '',
  I0 BIGINT DEFAULT 0,
  I1 BIGINT DEFAULT 0,
  I2 BIGINT DEFAULT 0,
  I3 BIGINT DEFAULT 0,
  I4 BIGINT DEFAULT 0,
  I5 BIGINT DEFAULT 0,
  I6 BIGINT DEFAULT 0,
  I7 BIGINT DEFAULT 0,
  I8 BIGINT DEFAULT 0,
  I9 BIGINT DEFAULT 0,
  I10 BIGINT DEFAULT 0,
  I11 BIGINT DEFAULT 0,
  I12 BIGINT DEFAULT 0,
  I13 BIGINT DEFAULT 0,
  I14 BIGINT DEFAULT 0,
  I15 BIGINT DEFAULT 0,
  I16 BIGINT DEFAULT 0,
  I17 BIGINT DEFAULT 0,
  I18 BIGINT DEFAULT 0,
  I19 BIGINT DEFAULT 0,
  I20 BIGINT DEFAULT 0,
  I21 BIGINT DEFAULT 0,
  I22 BIGINT DEFAULT 0,
  I23 BIGINT DEFAULT 0,
  I24 BIGINT DEFAULT 0,
  I25 BIGINT DEFAULT 0,
  I26 BIGINT DEFAULT 0,
  I27 BIGINT DEFAULT 0,
  I28 BIGINT DEFAULT 0,
  I29 BIGINT DEFAULT 0,
  I30 BIGINT DEFAULT 0,
  I31 BIGINT DEFAULT 0,
  I32 BIGINT DEFAULT 0,
  I33 BIGINT DEFAULT 0,
  I34 BIGINT DEFAULT 0,
  I35 BIGINT DEFAULT 0,
  I36 BIGINT DEFAULT 0,
  I37 BIGINT DEFAULT 0,
  I38 BIGINT DEFAULT 0,
  Checked INT DEFAULT 0,
  Lhand BIGINT DEFAULT 0,
  Rhand BIGINT DEFAULT 0,
  Spellone BIGINT DEFAULT 0,
  Spelltwo BIGINT DEFAULT 0,
  Accx INT DEFAULT 0,
  Tradex INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Clans table
CREATE TABLE IF NOT EXISTS Clans (
  Cid INT AUTO_INCREMENT PRIMARY KEY,
  Cname VARCHAR(100) NOT NULL,
  Cint INT DEFAULT 0,
  Cint2 INT DEFAULT NULL,
  Cleader VARCHAR(100) DEFAULT '',
  Cleader2 VARCHAR(100) DEFAULT '',
  Cpower INT DEFAULT 0,
  Cbonus INT DEFAULT 0,
  Cduels INT DEFAULT 0,
  Cturn INT DEFAULT 0,
  Cgold INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Kingdoms table
CREATE TABLE IF NOT EXISTS Kingdoms (
  Kd_loc INT PRIMARY KEY,
  Kd_clan INT DEFAULT 0,
  Kd_name VARCHAR(100) DEFAULT '',
  Kd_desc TEXT DEFAULT NULL,
  Kd_gold INT DEFAULT 0,
  Kd_str INT DEFAULT 0,
  Kd_def INT DEFAULT 0,
  Kd_race INT DEFAULT 0,
  Kd_bonus INT DEFAULT 1,
  Kd_gem INT DEFAULT 0,
  Kd_fame INT DEFAULT 10000000
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Housing table
CREATE TABLE IF NOT EXISTS Housing (
  H_loc INT PRIMARY KEY,
  H_owner INT DEFAULT NULL,
  H_name VARCHAR(100) DEFAULT '',
  H_desc TEXT DEFAULT NULL,
  H_pos INT DEFAULT 0,
  H_i0 BIGINT DEFAULT 0,
  H_i1 BIGINT DEFAULT 0,
  H_i2 BIGINT DEFAULT 0,
  H_i3 BIGINT DEFAULT 0,
  H_i4 BIGINT DEFAULT 0,
  H_i5 BIGINT DEFAULT 0,
  H_i6 BIGINT DEFAULT 0,
  H_i7 BIGINT DEFAULT 0,
  H_i8 BIGINT DEFAULT 0,
  H_i9 BIGINT DEFAULT 0,
  H_i10 BIGINT DEFAULT 0,
  H_i11 BIGINT DEFAULT 0,
  H_i12 BIGINT DEFAULT 0,
  H_i13 BIGINT DEFAULT 0,
  H_i14 BIGINT DEFAULT 0,
  H_i15 BIGINT DEFAULT 0,
  H_i16 BIGINT DEFAULT 0,
  H_i17 BIGINT DEFAULT 0,
  H_i18 BIGINT DEFAULT 0,
  H_i19 BIGINT DEFAULT 0,
  H_i20 BIGINT DEFAULT 0,
  H_i21 BIGINT DEFAULT 0,
  H_i22 BIGINT DEFAULT 0,
  H_i23 BIGINT DEFAULT 0,
  H_i24 BIGINT DEFAULT 0,
  H_i25 BIGINT DEFAULT 0,
  H_i26 BIGINT DEFAULT 0,
  H_i27 BIGINT DEFAULT 0,
  H_i28 BIGINT DEFAULT 0,
  H_i29 BIGINT DEFAULT 0,
  H_i30 BIGINT DEFAULT 0,
  H_i31 BIGINT DEFAULT 0,
  H_i32 BIGINT DEFAULT 0,
  H_i33 BIGINT DEFAULT 0,
  H_i34 BIGINT DEFAULT 0,
  H_i35 BIGINT DEFAULT 0,
  H_i36 BIGINT DEFAULT 0,
  H_i37 BIGINT DEFAULT 0,
  H_i38 BIGINT DEFAULT 0,
  H_i39 BIGINT DEFAULT 0,
  H_i40 BIGINT DEFAULT 0,
  H_i41 BIGINT DEFAULT 0,
  H_i42 BIGINT DEFAULT 0,
  H_i43 BIGINT DEFAULT 0,
  H_i44 BIGINT DEFAULT 0,
  H_i45 BIGINT DEFAULT 0,
  H_i46 BIGINT DEFAULT 0,
  H_i47 BIGINT DEFAULT 0,
  H_i48 BIGINT DEFAULT 0,
  H_i49 BIGINT DEFAULT 0,
  H_i50 BIGINT DEFAULT 0,
  H_extra1 VARCHAR(255) DEFAULT '',
  H_extra2 VARCHAR(255) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Messages table: in-game messaging
CREATE TABLE IF NOT EXISTS Messages (
  Id INT DEFAULT 0,
  Sender VARCHAR(100) DEFAULT '',
  Msg TEXT DEFAULT NULL,
  Msgtype INT DEFAULT 0,
  Ts DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Transfers table: item/gold transfers
CREATE TABLE IF NOT EXISTS Transfers (
  Tfrom VARCHAR(100) DEFAULT '',
  Tto VARCHAR(100) DEFAULT '',
  Titem BIGINT DEFAULT 0,
  Ts DATETIME DEFAULT NULL,
  Ttype INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Market table
CREATE TABLE IF NOT EXISTS Market (
  Mid INT AUTO_INCREMENT PRIMARY KEY,
  Seller_id INT DEFAULT 0,
  Buyer_id INT DEFAULT 0,
  Item BIGINT DEFAULT 0,
  Price INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Buddy list
CREATE TABLE IF NOT EXISTS Buddy (
  Id INT DEFAULT 0,
  BuddyId INT DEFAULT 0,
  Status INT DEFAULT 0,
  Ts DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Wedding system
CREATE TABLE IF NOT EXISTS Wedding (
  PId1 INT DEFAULT 0,
  PId2 INT DEFAULT 0,
  Status INT DEFAULT 0,
  Ts DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Player Kill Log
CREATE TABLE IF NOT EXISTS PKLog (
  PlayerId INT DEFAULT 0,
  KilledId INT DEFAULT 0,
  TS DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- PK Tags (custom kill messages)
CREATE TABLE IF NOT EXISTS PKTag (
  Id INT PRIMARY KEY,
  Pktag TEXT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Quests table
CREATE TABLE IF NOT EXISTS Quests (
  Qmon INT DEFAULT 0,
  Mlist TEXT DEFAULT NULL,
  Qzone INT DEFAULT 0,
  Qexp INT DEFAULT 0,
  Qgold INT DEFAULT 0,
  Qitem BIGINT DEFAULT 0,
  Qtype VARCHAR(10) DEFAULT 'x',
  Qnum INT DEFAULT 0,
  Qlevel INT DEFAULT 0,
  Qdone INT DEFAULT 0,
  Qmin INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Moderator action log
CREATE TABLE IF NOT EXISTS Modactions (
  Modname VARCHAR(100) DEFAULT '',
  Target VARCHAR(100) DEFAULT '',
  Action TEXT DEFAULT NULL,
  Ts DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Login tracking
CREATE TABLE IF NOT EXISTS Login (
  Id INT DEFAULT 0,
  Name VARCHAR(100) DEFAULT '',
  Ts DATETIME DEFAULT NULL,
  Ip VARCHAR(45) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Reservation (for name reservation during resets)
CREATE TABLE IF NOT EXISTS Reservation (
  Name VARCHAR(100) DEFAULT '',
  Password VARCHAR(255) DEFAULT '',
  Login VARCHAR(100) DEFAULT '',
  Channels INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- IP Bans
CREATE TABLE IF NOT EXISTS Ipban (
  Ip VARCHAR(45) NOT NULL,
  Ts DATETIME DEFAULT NULL,
  Name VARCHAR(100) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Fame rankings
CREATE TABLE IF NOT EXISTS Fame (
  Id INT DEFAULT 0,
  Name VARCHAR(100) DEFAULT '',
  Fame INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Zones
CREATE TABLE IF NOT EXISTS Zones (
  Zid INT PRIMARY KEY,
  Zname VARCHAR(100) DEFAULT '',
  Zdesc TEXT DEFAULT NULL,
  Ztype INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Races
CREATE TABLE IF NOT EXISTS Races (
  Rid INT PRIMARY KEY,
  Rname VARCHAR(100) DEFAULT '',
  R_str INT DEFAULT 0,
  R_dex INT DEFAULT 0,
  R_vit INT DEFAULT 0,
  R_ntl INT DEFAULT 0,
  R_wis INT DEFAULT 0,
  R_hp INT DEFAULT 0,
  R_gold INT DEFAULT 0,
  R_level INT DEFAULT 0,
  R_orb BIGINT DEFAULT 0,
  R_orbequip INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Database stats
CREATE TABLE IF NOT EXISTS db_stats (
  Stat_name VARCHAR(50) PRIMARY KEY,
  Stat_value INT DEFAULT 0,
  Date_modified DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Chat tables (4 separate chat channels)
CREATE TABLE IF NOT EXISTS chat1 (
  Msgnum INT AUTO_INCREMENT PRIMARY KEY,
  Msgname VARCHAR(100) DEFAULT '',
  Msgtxt TEXT DEFAULT NULL,
  Msgtype VARCHAR(10) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS chat2 (
  Msgnum INT AUTO_INCREMENT PRIMARY KEY,
  Msgname VARCHAR(100) DEFAULT '',
  Msgtxt TEXT DEFAULT NULL,
  Msgtype VARCHAR(10) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS chat3 (
  Msgnum INT AUTO_INCREMENT PRIMARY KEY,
  Msgname VARCHAR(100) DEFAULT '',
  Msgtxt TEXT DEFAULT NULL,
  Msgtype VARCHAR(10) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS chat4 (
  Msgnum INT AUTO_INCREMENT PRIMARY KEY,
  Msgname VARCHAR(100) DEFAULT '',
  Msgtxt TEXT DEFAULT NULL,
  Msgtype VARCHAR(10) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed data: create the required fake clan (cid 200)
INSERT INTO Clans (Cid, Cname, Cint, Cint2, Cleader, Cleader2, Cpower, Cbonus, Cduels, Cturn, Cgold)
VALUES (200, 'System', 0, NULL, 'System', '', 0, 0, 0, 0, 0);

-- Seed db_stats
INSERT INTO db_stats (Stat_name, Stat_value, Date_modified) VALUES ('Total', 0, NOW());
INSERT INTO db_stats (Stat_name, Stat_value, Date_modified) VALUES ('Inactive', 0, NOW());
INSERT INTO db_stats (Stat_name, Stat_value, Date_modified) VALUES ('Muted', 0, NOW());
INSERT INTO db_stats (Stat_name, Stat_value, Date_modified) VALUES ('Banned', 0, NOW());
